## -*- encoding: utf-8 -*-
## This file (./parentFunctions-Practice1-figure1.sagetex.sage) was *autogenerated* from ./parentFunctions-Practice1-figure1.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('./parentFunctions-Practice1-figure1', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
