## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file functionComposition-Practice1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_40 = Integer(40); _sage_const_67 = Integer(67); _sage_const_49 = Integer(49); _sage_const_6883 = Integer(6883); _sage_const_7919 = Integer(7919); _sage_const_179 = Integer(179); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_1000 = Integer(1000); _sage_const_58 = Integer(58); _sage_const_35 = Integer(35); _sage_const_7907 = Integer(7907)## This file (functionComposition-Practice1.sagetex.sage) was *autogenerated* from functionComposition-Practice1.tex with sagetex.sty version 2019/01/09 v3.2.
import sagetex
_st_ = sagetex.SageTeXProcessor('functionComposition-Practice1', version='2019/01/09 v3.2', version_check=True)
_st_.current_tex_line = _sage_const_1 
_st_.blockbegin()
try:
 
 ######  Define a function to convert a sage number into a saved counter number.
 
 def setCounter(counterName, counterValue, fileName = 'counters.tex'):
     file1 = open(fileName, 'w')
     counterString = str(r'\setcounter{' + str(counterName) + '}{'+ str(counterValue) +'}')
     commandString = str('\\newcommand{\\' + str(counterName) + '}{'+ str(counterValue) +'}')
     file1.write(counterString + "\n" + commandString + "\n")
     # more "string# =" and "file#.write()" as desired.
 
 
 
 #####Define default Sage variables.
 #Default function variables
 var('x,y,z,X,Y,Z')
 #Default function names
 var('f,g,h,dx,dy,dz,dh,df')
 #Default Wild cards
 w0 = SR.wild(_sage_const_0 )
 
 def DispSign(b):
     """ Returns the string of the 'signed' version of `b`, e.g. 3 -> "+3", -3 -> "-3", 0 -> "".
     """
     if b == _sage_const_0 :
         return ""
     elif b > _sage_const_0 :
         return "+" + str(b)
     elif b < _sage_const_0 :
         return str(b)
     else:
         # If we're here, then something has gone wrong.
         raise ValueError
 
 def ISP(b):
     return DispSign(b)
 
 def NoEval(f, c):
     # TODO
     """ Returns a non-evaluted version of the result f(c).
     """
     cStr = str(c)
     # fLatex = latex(f)
     fString = latex(f)
     fStrList = list(fString)
     length = len(fStrList)
     fStrList2 = range(length)
     for i in range(_sage_const_0 , length):
         if fStrList[i] == "x":
             fStrList2[i] = "("+cstr+")"
         else:
             fStrList2[i] = fStrList[i]
     f2 = join(fStrList2,"")
     return LatexExpr(f2)
 
 def HyperSimp(f):
     """ Returns the expression `f` without hyperbolic expressions.
     """
     subsDict = {
         sinh(w0) : (exp(w0) - exp(-w0))/_sage_const_2 ,
         cosh(w0) : (exp(w0) + exp(-w0))/_sage_const_2 ,
         tanh(w0) : (exp(w0) - exp(-w0))/(exp(w0) + exp(-w0)),
         sech(w0) : _sage_const_2 /(exp(w0) + exp(-w0)),                      # This seems to work, but Nowell said it didn't at one point.
         csch(w0) : _sage_const_2 /(exp(w0) - exp(-w0)),                      # This seems to work, but Nowell said it didn't at one point.
         coth(w0) : (exp(w0) + exp(-w0))/(exp(w0) - exp(-w0)),   # This seems to work, but Nowell said it didn't at one point.
         arcsinh(w0) :       ln( w0 + sqrt((w0)**_sage_const_2  + _sage_const_1 ) ),
         arccosh(w0) :       ln( w0 + sqrt((w0)**_sage_const_2  - _sage_const_1 ) ),
         arctanh(w0) : _sage_const_1 /_sage_const_2  * ln( (_sage_const_1  + w0) / (_sage_const_1  - w0) ),
         arccsch(w0) :       ln( (_sage_const_1  + sqrt((w0)**_sage_const_2  + _sage_const_1 ))/w0 ),
         arcsech(w0) :       ln( (_sage_const_1  + sqrt(_sage_const_1  - (w0)**_sage_const_2 ))/w0 ),
         arccoth(w0) : _sage_const_1 /_sage_const_2  * ln( (_sage_const_1  + w0) / (w0 - _sage_const_1 ) )
     }
     g = f.substitute(subsDict)
     return simplify(g)
 
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a
 
 #def RandAng(s,t):
 #    """ Returns a random nice angle in [0,2*pi] which lies in [`s`,`t`].
 #    """
 #    angles = [i*pi/6 for i in range(0,13)] + [(2*i+1)*pi/4 for i in range(0,4)]
 #    while True:
 #        angle = choice(angles) # Picks a random element.
 #        if s <= angle <= t:
 #            return simplify(angle)
 
 def RandPoly(degree, zeroes=[], avoid=[], monic=False, expanded=False):
     """Note: If you want a polynomial of degree 4 with a zero at x=3 of
     multiplicity 2, for example, you should call
     >>> RandPoly(4, zeroes = [3,3], avoid = [3])
     (x-3)^2*(x+1)*(x-5)
     """
     RP_missingDegree = degree - len(zeroes)
     assert RP_missingDegree >= _sage_const_0 , "Can't have degree {} with all those zeroes! {}".format(degree,zeroes)
     # First, compute the part that has the specified zeroes.
     if monic:
         RP_myRandomPoly = prod((x-RP_zero) for RP_zero in zeroes)
     else:
         RP_myRandomPoly = prod((RP_zero.denominator()*x - RP_zero.numerator()) for RP_zero in zeroes)
     # Second, compute the missing factor.
     if avoid:
         RP_missingZeroes =[NonZeroInt(-_sage_const_10 ,_sage_const_10 ,avoid) for RP_ in range(RP_missingDegree)]
         RP_missingFactor = prod((x-RP_missingZero) for RP_missingZero in RP_missingZeroes)
     else:
         if monic:
             RP_missingFactor = x**RP_missingDegree
         else:
             RP_missingFactor = NonZeroInt(-_sage_const_10 ,_sage_const_10 )*x**RP_missingDegree
 
         for RP_i in range(_sage_const_0 ,RP_missingDegree):
             RP_missingFactor += RandInt(-_sage_const_10 ,_sage_const_10 )*x**RP_i
     RP_myRandomPoly *= RP_missingFactor
     if expanded:
         RP_myRandomPoly = expand(RP_myRandomPoly)
     return RP_myRandomPoly
 
 def RandRational(c,d):
     """ Returns a random rational function with numerator and denominator of degrees `c` and `d` resp.
     """
     num_zeros = [RandInt(-_sage_const_10 ,_sage_const_10 ) for _ in range(c)] # Zeroes of the numerator
     num = RandPoly(c,zeroes=num_zeroes) # Numerator
     den = RandPoly(d,avoid =num_zeroes) # Denominator
     return num/den
 
 def saneCheck(a,b = _sage_const_1000 ):
     """ A function to check the reasonable-ness of an answer. It checks the
         numerator and denominator to see if they are reasonable numbers. `a` is
         the input number to check, and b is the threshold you want the numerator
         and denominator (if present) to be below. Default is 1000. Thus 1/596
         would pass, 5419/209 would not.
     """
     aTemp = abs(a/(_sage_const_7919 *_sage_const_7907 *_sage_const_6883 )) # I need to force a denominator. Odds are, whatever you're checking won't have all these primes as factors. If they do, then you have fucked up royally anyway. Also take absolute value in order to test magnitude of values.
     # Initialize answer to -1 to detect if anything happened.
     check = -_sage_const_1 
     if aTemp.numerator() > b or aTemp.denominator() > (b*_sage_const_7919 *_sage_const_7907 *_sage_const_6883 ):
         check = _sage_const_0 
     else:
         check = _sage_const_1 
     return check
 
 def RandVector(b, c, avoid=[], rep=_sage_const_1 ):
     """ Returns essentially a multiset permutation of ([b,c]-av) * rep.
         That is, a vector which contains each integer in [`b`,`c`] which is not in `av` a total of `rep` number of times.
         Example:
         sage: RandVector(1,3, [2], 2)
         [3, 1, 1, 3]
     """
     oneVec = [val for val in range(b,c+_sage_const_1 ) if val not in avoid]
     vec = oneVec * rep
     shuffle(vec)
     return vec
 
 def RandMatrix(dim1, dim2, LBnum,UBnum,LBden,UBden):
     """ Returns a random matrix with rational entries.
         The final four parameters specify lower and upper bounds for the
         numerators and denominators of the entries.
     """
     temp = matrix(QQ, dim1, dim2, _sage_const_0 )
     for i in range(dim1):
         for j in range(dim2):
             num = RandInt(LBnum, UBnum)
             den = NonZeroInt(LBden, UBden)
             temp[i,j] = num/den
     return temp
 
except:
 _st_.goboom(_sage_const_179 )
_st_.blockend()
_st_.current_tex_line = _sage_const_6 
_st_.blockbegin()
try:
 ###### Problem p1
 p1c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1f1 = expand((x+p1c1)*(x+p1c2))
 
 
 
 ###### Problem p2
 p2c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p2c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p2f1 = expand((x+p2c1)*(x+p2c2))
 
 
 
 ###### Problem p3
 p3c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p3c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p3f1 = expand((x+p3c1)*(x+p3c2))
 
 
 
 ###### Problem p4
 p4c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p4c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p4f1 = expand((x+p4c1)*(x+p4c2))
 
 
 
except:
 _st_.goboom(_sage_const_35 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_40 
 _st_.inline(_sage_const_0 , latex(p1f1))
except:
 _st_.goboom(_sage_const_40 )
try:
 _st_.current_tex_line = _sage_const_40 
 _st_.inline(_sage_const_1 , latex(x + p1c1))
except:
 _st_.goboom(_sage_const_40 )
try:
 _st_.current_tex_line = _sage_const_40 
 _st_.inline(_sage_const_2 , latex(x + p1c2))
except:
 _st_.goboom(_sage_const_40 )
try:
 _st_.current_tex_line = _sage_const_49 
 _st_.inline(_sage_const_3 , latex(p2f1))
except:
 _st_.goboom(_sage_const_49 )
try:
 _st_.current_tex_line = _sage_const_49 
 _st_.inline(_sage_const_4 , latex(x + p2c1))
except:
 _st_.goboom(_sage_const_49 )
try:
 _st_.current_tex_line = _sage_const_49 
 _st_.inline(_sage_const_5 , latex(x + p2c2))
except:
 _st_.goboom(_sage_const_49 )
try:
 _st_.current_tex_line = _sage_const_58 
 _st_.inline(_sage_const_6 , latex(p3f1))
except:
 _st_.goboom(_sage_const_58 )
try:
 _st_.current_tex_line = _sage_const_58 
 _st_.inline(_sage_const_7 , latex(x + p3c1))
except:
 _st_.goboom(_sage_const_58 )
try:
 _st_.current_tex_line = _sage_const_58 
 _st_.inline(_sage_const_8 , latex(x + p3c2))
except:
 _st_.goboom(_sage_const_58 )
try:
 _st_.current_tex_line = _sage_const_67 
 _st_.inline(_sage_const_9 , latex(p4f1))
except:
 _st_.goboom(_sage_const_67 )
try:
 _st_.current_tex_line = _sage_const_67 
 _st_.inline(_sage_const_10 , latex(x + p4c1))
except:
 _st_.goboom(_sage_const_67 )
try:
 _st_.current_tex_line = _sage_const_67 
 _st_.inline(_sage_const_11 , latex(x + p4c2))
except:
 _st_.goboom(_sage_const_67 )
_st_.endofdoc()

