## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file simplifyNumericLogs-Practice1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_500 = Integer(500); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_9999 = Integer(9999); _sage_const_81 = Integer(81); _sage_const_68 = Integer(68); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_59 = Integer(59); _sage_const_14 = Integer(14); _sage_const_57 = Integer(57); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_15 = Integer(15); _sage_const_51 = Integer(51); _sage_const_70 = Integer(70); _sage_const_92 = Integer(92); _sage_const_90 = Integer(90); _sage_const_79 = Integer(79); _sage_const_95 = Integer(95)## This file (simplifyNumericLogs-Practice1.sagetex.sage) was *autogenerated* from simplifyNumericLogs-Practice1.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('simplifyNumericLogs-Practice1', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_1 
_st_.blockbegin()
try:
 
 ######  Define a function to convert a sage number into a saved counter number.
 
 #####Define default Sage variables.
 #Default function variables
 var('x,y,z,X,Y,Z')
 #Default function names
 var('f,g,h,dx,dy,dz,dh,df')
 #Default Wild cards
 w0 = SR.wild(_sage_const_0 )
 
 def DispSign(b):
     """ Returns the string of the 'signed' version of `b`, e.g. 3 -> "+3", -3 -> "-3", 0 -> "".
     """
     if b == _sage_const_0 :
         return ""
     elif b > _sage_const_0 :
         return "+" + str(b)
     elif b < _sage_const_0 :
         return str(b)
     else:
         # If we're here, then something has gone wrong.
         raise ValueError
 
 def ISP(b):
     return DispSign(b)
 
 def NoEval(f, c):
     # TODO
     """ Returns a non-evaluted version of the result f(c).
     """
     cStr = str(c)
     # fLatex = latex(f)
     fString = latex(f)
     fStrList = list(fString)
     length = len(fStrList)
     fStrList2 = range(length)
     for i in range(_sage_const_0 , length):
         if fStrList[i] == "x":
             fStrList2[i] = "("+cstr+")"
         else:
             fStrList2[i] = fStrList[i]
     f2 = join(fStrList2,"")
     return LatexExpr(f2)
 
 def HyperSimp(f):
     """ Returns the expression `f` without hyperbolic expressions.
     """
     subsDict = {
         sinh(w0) : (exp(w0) - exp(-w0))/_sage_const_2 ,
         cosh(w0) : (exp(w0) + exp(-w0))/_sage_const_2 ,
         tanh(w0) : (exp(w0) - exp(-w0))/(exp(w0) + exp(-w0)),
         sech(w0) : _sage_const_2 /(exp(w0) + exp(-w0)),                      # This seems to work, but Nowell said it didn't at one point.
         csch(w0) : _sage_const_2 /(exp(w0) - exp(-w0)),                      # This seems to work, but Nowell said it didn't at one point.
         coth(w0) : (exp(w0) + exp(-w0))/(exp(w0) - exp(-w0)),   # This seems to work, but Nowell said it didn't at one point.
         arcsinh(w0) :       ln( w0 + sqrt((w0)**_sage_const_2  + _sage_const_1 ) ),
         arccosh(w0) :       ln( w0 + sqrt((w0)**_sage_const_2  - _sage_const_1 ) ),
         arctanh(w0) : _sage_const_1 /_sage_const_2  * ln( (_sage_const_1  + w0) / (_sage_const_1  - w0) ),
         arccsch(w0) :       ln( (_sage_const_1  + sqrt((w0)**_sage_const_2  + _sage_const_1 ))/w0 ),
         arcsech(w0) :       ln( (_sage_const_1  + sqrt(_sage_const_1  - (w0)**_sage_const_2 ))/w0 ),
         arccoth(w0) : _sage_const_1 /_sage_const_2  * ln( (_sage_const_1  + w0) / (w0 - _sage_const_1 ) )
     }
     g = f.substitute(subsDict)
     return simplify(g)
 
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a
 
 def RandVector(b, c, avoid=[], rep=_sage_const_1 ):
     """ Returns essentially a multiset permutation of ([b,c]-av) * rep.
         That is, a vector which contains each integer in [`b`,`c`] which is not in `av` a total of `rep` number of times.
         Example:
         sage: RandVector(1,3, [2], 2)
         [3, 1, 1, 3]
     """
     oneVec = [val for val in range(b,c+_sage_const_1 ) if val not in avoid]
     vec = oneVec * rep
     shuffle(vec)
     return vec
 
 
except:
 _st_.goboom(_sage_const_95 )
_st_.blockend()
_st_.current_tex_line = _sage_const_9 
_st_.blockbegin()
try:
 
 ##### Problem p1
 p1b1 = RandInt(_sage_const_2 ,_sage_const_7 )
 p1arg1 = _sage_const_9999 
 while p1arg1 > _sage_const_500 :
     p1pwr1 = RandInt(_sage_const_0 ,_sage_const_5 )
     p1arg1 = p1b1**p1pwr1
     p1arg2 = p1b1**(-p1pwr1)
 p1ans1 = p1pwr1
 p1ans2 = -p1pwr1
 
 ##### Problem p2
 p2b1 = RandInt(_sage_const_2 ,_sage_const_7 )
 p2arg1 = _sage_const_9999 
 while p2arg1 > _sage_const_500 :
     p2pwr1 = RandInt(_sage_const_0 ,_sage_const_5 )
     p2arg1 = p2b1**p2pwr1
     p2arg2 = p2b1**(-p2pwr1)
 p2ans1 = p2pwr1
 p2ans2 = -p2pwr1
 
 ##### Problem p3
 p3b1 = RandInt(_sage_const_2 ,_sage_const_7 )
 p3arg1 = _sage_const_9999 
 while p3arg1 > _sage_const_500 :
     p3pwr1 = RandInt(_sage_const_0 ,_sage_const_5 )
     p3arg1 = p3b1**p3pwr1
     p3arg2 = p3b1**(-p3pwr1)
 p3ans1 = p3pwr1
 p3ans2 = -p3pwr1
 
 ##### Problem p4
 p4pwr1 = RandInt(_sage_const_0 ,_sage_const_5 )
 p4arg1 = _sage_const_9999 
 while p4arg1 > _sage_const_500 :
     p4b1 = RandInt(_sage_const_2 ,_sage_const_7 )
     p4arg1 = p4b1**p4pwr1
     p4arg2 = p4b1**(-p4pwr1)
 p4ans1 = p4pwr1
 p4ans2 = -p4pwr1
 
except:
 _st_.goboom(_sage_const_51 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_57 
 _st_.inline(_sage_const_0 , latex(p1b1))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.current_tex_line = _sage_const_57 
 _st_.inline(_sage_const_1 , latex(p1arg1))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.current_tex_line = _sage_const_57 
 _st_.inline(_sage_const_2 , latex(p1ans1))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_3 , latex(p1b1))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_4 , latex(p1arg2))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_5 , latex(p1ans2))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_68 
 _st_.inline(_sage_const_6 , latex(p2b1))
except:
 _st_.goboom(_sage_const_68 )
try:
 _st_.current_tex_line = _sage_const_68 
 _st_.inline(_sage_const_7 , latex(p2arg1))
except:
 _st_.goboom(_sage_const_68 )
try:
 _st_.current_tex_line = _sage_const_68 
 _st_.inline(_sage_const_8 , latex(p2ans1))
except:
 _st_.goboom(_sage_const_68 )
try:
 _st_.current_tex_line = _sage_const_70 
 _st_.inline(_sage_const_9 , latex(p2b1))
except:
 _st_.goboom(_sage_const_70 )
try:
 _st_.current_tex_line = _sage_const_70 
 _st_.inline(_sage_const_10 , latex(p2arg2))
except:
 _st_.goboom(_sage_const_70 )
try:
 _st_.current_tex_line = _sage_const_70 
 _st_.inline(_sage_const_11 , latex(p2ans2))
except:
 _st_.goboom(_sage_const_70 )
try:
 _st_.current_tex_line = _sage_const_79 
 _st_.inline(_sage_const_12 , latex(p3b1))
except:
 _st_.goboom(_sage_const_79 )
try:
 _st_.current_tex_line = _sage_const_79 
 _st_.inline(_sage_const_13 , latex(p3arg1))
except:
 _st_.goboom(_sage_const_79 )
try:
 _st_.current_tex_line = _sage_const_79 
 _st_.inline(_sage_const_14 , latex(p3ans1))
except:
 _st_.goboom(_sage_const_79 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_15 , latex(p3b1))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_16 , latex(p3arg2))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_17 , latex(p3ans2))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_18 , latex(p4b1))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_19 , latex(p4arg1))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_20 , latex(p4ans1))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_92 
 _st_.inline(_sage_const_21 , latex(p4b1))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.current_tex_line = _sage_const_92 
 _st_.inline(_sage_const_22 , latex(p4arg2))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.current_tex_line = _sage_const_92 
 _st_.inline(_sage_const_23 , latex(p4ans2))
except:
 _st_.goboom(_sage_const_92 )
_st_.endofdoc()

