## -*- encoding: utf-8 -*-
## This file (./rigidTranslationsGeometric-Practice1-figure4.sagetex.sage) was *autogenerated* from ./rigidTranslationsGeometric-Practice1-figure4.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('./rigidTranslationsGeometric-Practice1-figure4', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
