## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file rigidTranslationsAnalytic-Practice1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_66 = Integer(66); _sage_const_89 = Integer(89); _sage_const_80 = Integer(80); _sage_const_82 = Integer(82); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_98 = Integer(98); _sage_const_71 = Integer(71); _sage_const_73 = Integer(73); _sage_const_100 = Integer(100); _sage_const_91 = Integer(91)## This file (rigidTranslationsAnalytic-Practice1.sagetex.sage) was *autogenerated* from rigidTranslationsAnalytic-Practice1.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('rigidTranslationsAnalytic-Practice1', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_10 
_st_.blockbegin()
try:
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 #### Problem p1
 p1c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1c3 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1c4 = RandInt(-_sage_const_10 ,_sage_const_10 )
 
 p1i1 = x - p1c1
 
 p1ans1 = p1c3 + p1c1
 p1ans2 = p1c2 + p1c4
 
 
 #### Problem p2
 p2c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p2c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p2c3 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p2c4 = RandInt(-_sage_const_10 ,_sage_const_10 )
 
 p2i1 = x - p2c1
 
 p2ans1 = p2c3 + p2c1
 p2ans2 = p2c2 + p2c4
 
 
 #### Problem p3
 p3c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p3c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p3c3 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p3c4 = RandInt(-_sage_const_10 ,_sage_const_10 )
 
 p3i1 = x - p3c1
 
 p3ans1 = p3c3 + p3c1
 p3ans2 = p3c2 + p3c4
 
 
 #### Problem p4
 p4c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p4c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p4c3 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p4c4 = RandInt(-_sage_const_10 ,_sage_const_10 )
 
 p4i1 = x - p4c1
 
 p4ans1 = p4c3 + p4c1
 p4ans2 = p4c2 + p4c4
 
 
 
except:
 _st_.goboom(_sage_const_66 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_71 
 _st_.inline(_sage_const_0 , latex(p1i1))
except:
 _st_.goboom(_sage_const_71 )
try:
 _st_.current_tex_line = _sage_const_71 
 _st_.inline(_sage_const_1 , latex(p1c2))
except:
 _st_.goboom(_sage_const_71 )
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.inline(_sage_const_2 , latex(p1c3))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.inline(_sage_const_3 , latex(p1c4))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.inline(_sage_const_4 , latex(p1ans1))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.inline(_sage_const_5 , latex(p1ans2))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_6 , latex(p2i1))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_7 , latex(p2c2))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_82 
 _st_.inline(_sage_const_8 , latex(p2c3))
except:
 _st_.goboom(_sage_const_82 )
try:
 _st_.current_tex_line = _sage_const_82 
 _st_.inline(_sage_const_9 , latex(p2c4))
except:
 _st_.goboom(_sage_const_82 )
try:
 _st_.current_tex_line = _sage_const_82 
 _st_.inline(_sage_const_10 , latex(p2ans1))
except:
 _st_.goboom(_sage_const_82 )
try:
 _st_.current_tex_line = _sage_const_82 
 _st_.inline(_sage_const_11 , latex(p2ans2))
except:
 _st_.goboom(_sage_const_82 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_12 , latex(p3i1))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_13 , latex(p3c2))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_14 , latex(p3c3))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_15 , latex(p3c4))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_16 , latex(p3ans1))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_17 , latex(p3ans2))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_98 
 _st_.inline(_sage_const_18 , latex(p4i1))
except:
 _st_.goboom(_sage_const_98 )
try:
 _st_.current_tex_line = _sage_const_98 
 _st_.inline(_sage_const_19 , latex(p4c2))
except:
 _st_.goboom(_sage_const_98 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_20 , latex(p4c3))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_21 , latex(p4c4))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_22 , latex(p4ans1))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_23 , latex(p4ans2))
except:
 _st_.goboom(_sage_const_100 )
_st_.endofdoc()

