## -*- encoding: utf-8 -*-
## This file (./sectionReview-figure8.sagetex.sage) was *autogenerated* from ./sectionReview-figure8.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('./sectionReview-figure8', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
