## -*- encoding: utf-8 -*-
## This file (translationsAndTransformations-Practice1.sagetex.sage) was *autogenerated* from translationsAndTransformations-Practice1.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('translationsAndTransformations-Practice1', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
