## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file translationsAndTransformations-Practice1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_89 = Integer(89); _sage_const_84 = Integer(84); _sage_const_116 = Integer(116); _sage_const_114 = Integer(114); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_108 = Integer(108); _sage_const_98 = Integer(98); _sage_const_100 = Integer(100); _sage_const_91 = Integer(91); _sage_const_106 = Integer(106)## This file (translationsAndTransformations-Practice1.sagetex.sage) was *autogenerated* from translationsAndTransformations-Practice1.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('translationsAndTransformations-Practice1', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_10 
_st_.blockbegin()
try:
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a
 
 
 #### Problem p1
 p1c1 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ])
 p1c2 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ])
 p1c3 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1c4 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1c5 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1c6 = RandInt(-_sage_const_10 ,_sage_const_10 )
 
 p1i1 = p1c2*x - p1c3
 
 p1ans1 = (p1c3+p1c5)/p1c2
 p1ans2 = p1c6*p1c1 + p1c4
 
 
 #### Problem p2
 p2c1 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ])
 p2c2 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ])
 p2c3 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p2c4 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p2c5 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p2c6 = RandInt(-_sage_const_10 ,_sage_const_10 )
 
 p2i1 = p2c2*x - p2c3
 
 p2ans1 = (p2c3+p2c5)/p2c2
 p2ans2 = p2c6*p2c1 + p2c4
 
 
 #### Problem p3
 p3c1 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ])
 p3c2 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ])
 p3c3 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p3c4 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p3c5 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p3c6 = RandInt(-_sage_const_10 ,_sage_const_10 )
 
 p3i1 = p3c2*x - p3c3
 
 p3ans1 = (p3c3+p3c5)/p3c2
 p3ans2 = p3c6*p3c1 + p3c4
 
 
 #### Problem p4
 p4c1 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ])
 p4c2 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ])
 p4c3 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p4c4 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p4c5 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p4c6 = RandInt(-_sage_const_10 ,_sage_const_10 )
 
 p4i1 = p4c2*x - p4c3
 
 p4ans1 = (p4c3+p4c5)/p4c2
 p4ans2 = p4c6*p4c1 + p4c4
 
 
 
except:
 _st_.goboom(_sage_const_84 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_0 , latex(p1c1))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_1 , latex(p1i1))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_2 , latex(p1c4))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_3 , latex(p1c5))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_4 , latex(p1c6))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_5 , latex(p1ans1))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_6 , latex(p1ans2))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_98 
 _st_.inline(_sage_const_7 , latex(p2c1))
except:
 _st_.goboom(_sage_const_98 )
try:
 _st_.current_tex_line = _sage_const_98 
 _st_.inline(_sage_const_8 , latex(p2i1))
except:
 _st_.goboom(_sage_const_98 )
try:
 _st_.current_tex_line = _sage_const_98 
 _st_.inline(_sage_const_9 , latex(p2c4))
except:
 _st_.goboom(_sage_const_98 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_10 , latex(p2c5))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_11 , latex(p2c6))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_12 , latex(p2ans1))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_13 , latex(p2ans2))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_106 
 _st_.inline(_sage_const_14 , latex(p3c1))
except:
 _st_.goboom(_sage_const_106 )
try:
 _st_.current_tex_line = _sage_const_106 
 _st_.inline(_sage_const_15 , latex(p3i1))
except:
 _st_.goboom(_sage_const_106 )
try:
 _st_.current_tex_line = _sage_const_106 
 _st_.inline(_sage_const_16 , latex(p3c4))
except:
 _st_.goboom(_sage_const_106 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_17 , latex(p3c5))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_18 , latex(p3c6))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_19 , latex(p3ans1))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_20 , latex(p3ans2))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_21 , latex(p4c1))
except:
 _st_.goboom(_sage_const_114 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_22 , latex(p4i1))
except:
 _st_.goboom(_sage_const_114 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_23 , latex(p4c4))
except:
 _st_.goboom(_sage_const_114 )
try:
 _st_.current_tex_line = _sage_const_116 
 _st_.inline(_sage_const_24 , latex(p4c5))
except:
 _st_.goboom(_sage_const_116 )
try:
 _st_.current_tex_line = _sage_const_116 
 _st_.inline(_sage_const_25 , latex(p4c6))
except:
 _st_.goboom(_sage_const_116 )
try:
 _st_.current_tex_line = _sage_const_116 
 _st_.inline(_sage_const_26 , latex(p4ans1))
except:
 _st_.goboom(_sage_const_116 )
try:
 _st_.current_tex_line = _sage_const_116 
 _st_.inline(_sage_const_27 , latex(p4ans2))
except:
 _st_.goboom(_sage_const_116 )
_st_.endofdoc()

