## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file absoluteValueAnalyticViewpoint-Practice1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_28 = Integer(28); _sage_const_29 = Integer(29); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_135 = Integer(135); _sage_const_136 = Integer(136); _sage_const_89 = Integer(89); _sage_const_133 = Integer(133); _sage_const_84 = Integer(84); _sage_const_117 = Integer(117); _sage_const_116 = Integer(116); _sage_const_114 = Integer(114); _sage_const_155 = Integer(155); _sage_const_154 = Integer(154); _sage_const_152 = Integer(152); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_31 = Integer(31); _sage_const_30 = Integer(30); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_108 = Integer(108); _sage_const_98 = Integer(98); _sage_const_127 = Integer(127); _sage_const_97 = Integer(97); _sage_const_95 = Integer(95); _sage_const_146 = Integer(146)## This file (absoluteValueAnalyticViewpoint-Practice1.sagetex.sage) was *autogenerated* from absoluteValueAnalyticViewpoint-Practice1.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('absoluteValueAnalyticViewpoint-Practice1', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_1 
_st_.blockbegin()
try:
 
 ######  Define a function to convert a sage number into a saved counter number.
 
 #####Define default Sage variables.
 #Default function variables
 var('x,y,z,X,Y,Z')
 #Default function names
 var('f,g,h,dx,dy,dz,dh,df')
 #Default Wild cards
 w0 = SR.wild(_sage_const_0 )
 
 def DispSign(b):
     """ Returns the string of the 'signed' version of `b`, e.g. 3 -> "+3", -3 -> "-3", 0 -> "".
     """
     if b == _sage_const_0 :
         return ""
     elif b > _sage_const_0 :
         return "+" + str(b)
     elif b < _sage_const_0 :
         return str(b)
     else:
         # If we're here, then something has gone wrong.
         raise ValueError
 
 def ISP(b):
     return DispSign(b)
 
 def NoEval(f, c):
     # TODO
     """ Returns a non-evaluted version of the result f(c).
     """
     cStr = str(c)
     # fLatex = latex(f)
     fString = latex(f)
     fStrList = list(fString)
     length = len(fStrList)
     fStrList2 = range(length)
     for i in range(_sage_const_0 , length):
         if fStrList[i] == "x":
             fStrList2[i] = "("+cstr+")"
         else:
             fStrList2[i] = fStrList[i]
     f2 = join(fStrList2,"")
     return LatexExpr(f2)
 
 def HyperSimp(f):
     """ Returns the expression `f` without hyperbolic expressions.
     """
     subsDict = {
         sinh(w0) : (exp(w0) - exp(-w0))/_sage_const_2 ,
         cosh(w0) : (exp(w0) + exp(-w0))/_sage_const_2 ,
         tanh(w0) : (exp(w0) - exp(-w0))/(exp(w0) + exp(-w0)),
         sech(w0) : _sage_const_2 /(exp(w0) + exp(-w0)),                      # This seems to work, but Nowell said it didn't at one point.
         csch(w0) : _sage_const_2 /(exp(w0) - exp(-w0)),                      # This seems to work, but Nowell said it didn't at one point.
         coth(w0) : (exp(w0) + exp(-w0))/(exp(w0) - exp(-w0)),   # This seems to work, but Nowell said it didn't at one point.
         arcsinh(w0) :       ln( w0 + sqrt((w0)**_sage_const_2  + _sage_const_1 ) ),
         arccosh(w0) :       ln( w0 + sqrt((w0)**_sage_const_2  - _sage_const_1 ) ),
         arctanh(w0) : _sage_const_1 /_sage_const_2  * ln( (_sage_const_1  + w0) / (_sage_const_1  - w0) ),
         arccsch(w0) :       ln( (_sage_const_1  + sqrt((w0)**_sage_const_2  + _sage_const_1 ))/w0 ),
         arcsech(w0) :       ln( (_sage_const_1  + sqrt(_sage_const_1  - (w0)**_sage_const_2 ))/w0 ),
         arccoth(w0) : _sage_const_1 /_sage_const_2  * ln( (_sage_const_1  + w0) / (w0 - _sage_const_1 ) )
     }
     g = f.substitute(subsDict)
     return simplify(g)
 
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a
 
 def RandVector(b, c, avoid=[], rep=_sage_const_1 ):
     """ Returns essentially a multiset permutation of ([b,c]-av) * rep.
         That is, a vector which contains each integer in [`b`,`c`] which is not in `av` a total of `rep` number of times.
         Example:
         sage: RandVector(1,3, [2], 2)
         [3, 1, 1, 3]
     """
     oneVec = [val for val in range(b,c+_sage_const_1 ) if val not in avoid]
     vec = oneVec * rep
     shuffle(vec)
     return vec
 
 
except:
 _st_.goboom(_sage_const_95 )
_st_.blockend()
_st_.current_tex_line = _sage_const_11 
_st_.blockbegin()
try:
 #### Problem p1
 p1c1 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p1c2 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1c3 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1c4 = RandInt(-_sage_const_5 ,_sage_const_5 )
 
 p1f1 = p1c1*x - p1c2
 p1f2 = p1c3*x - p1c4
 
 if p1c1 > _sage_const_0 :
     p1ans1 = -p1f1 + p1f2
     p1ans2 = p1f1 + p1f2
 else:
     p1ans1 = p1f1 + p1f2
     p1ans2 = -p1f1 + p1f2
 p1ans3 = p1c2/p1c1
 
 
 #### Problem p2
 p2c1 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p2c2 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p2c3 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p2c4 = RandInt(-_sage_const_5 ,_sage_const_5 )
 
 p2f1 = p2c1*x - p2c2
 p2f2 = p2c3*x - p2c4
 
 if p2c1 > _sage_const_0 :
     p2ans1 = -p2f1 + p2f2
     p2ans2 = p2f1 + p2f2
 else:
     p2ans1 = p2f1 + p2f2
     p2ans2 = -p2f1 + p2f2
 p2ans3 = p2c2/p2c1
 
 
 #### Problem p3
 p3c1 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p3c2 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p3c3 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p3c4 = RandInt(-_sage_const_5 ,_sage_const_5 )
 
 p3f1 = p3c1*x - p3c2
 p3f2 = p3c3*x - p3c4
 
 if p3c1 > _sage_const_0 :
     p3ans1 = -p3f1 + p3f2
     p3ans2 = p3f1 + p3f2
 else:
     p3ans1 = p3f1 + p3f2
     p3ans2 = -p3f1 + p3f2
 p3ans3 = p3c2/p3c1
 
 
 #### Problem p4
 p4c1 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p4c2 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p4c3 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p4c4 = RandInt(-_sage_const_5 ,_sage_const_5 )
 
 p4f1 = p4c1*x - p4c2
 p4f2 = p4c3*x - p4c4
 
 if p4c1 > _sage_const_0 :
     p4ans1 = -p4f1 + p4f2
     p4ans2 = p4f1 + p4f2
 else:
     p4ans1 = p4f1 + p4f2
     p4ans2 = -p4f1 + p4f2
 p4ans3 = p4c2/p4c1
 
 
except:
 _st_.goboom(_sage_const_84 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_0 , latex(p1f1))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_1 , latex(p1f2))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_95 
 _st_.inline(_sage_const_2 , latex(p1f1))
except:
 _st_.goboom(_sage_const_95 )
try:
 _st_.current_tex_line = _sage_const_95 
 _st_.inline(_sage_const_3 , latex(p1f2))
except:
 _st_.goboom(_sage_const_95 )
try:
 _st_.current_tex_line = _sage_const_97 
 _st_.inline(_sage_const_4 , latex(p1ans1))
except:
 _st_.goboom(_sage_const_97 )
try:
 _st_.current_tex_line = _sage_const_97 
 _st_.inline(_sage_const_5 , latex(p1ans3))
except:
 _st_.goboom(_sage_const_97 )
try:
 _st_.current_tex_line = _sage_const_98 
 _st_.inline(_sage_const_6 , latex(p1ans2))
except:
 _st_.goboom(_sage_const_98 )
try:
 _st_.current_tex_line = _sage_const_98 
 _st_.inline(_sage_const_7 , latex(p1ans3))
except:
 _st_.goboom(_sage_const_98 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_8 , latex(p2f1))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_9 , latex(p2f2))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_10 , latex(p2f1))
except:
 _st_.goboom(_sage_const_114 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_11 , latex(p2f2))
except:
 _st_.goboom(_sage_const_114 )
try:
 _st_.current_tex_line = _sage_const_116 
 _st_.inline(_sage_const_12 , latex(p2ans1))
except:
 _st_.goboom(_sage_const_116 )
try:
 _st_.current_tex_line = _sage_const_116 
 _st_.inline(_sage_const_13 , latex(p2ans3))
except:
 _st_.goboom(_sage_const_116 )
try:
 _st_.current_tex_line = _sage_const_117 
 _st_.inline(_sage_const_14 , latex(p2ans2))
except:
 _st_.goboom(_sage_const_117 )
try:
 _st_.current_tex_line = _sage_const_117 
 _st_.inline(_sage_const_15 , latex(p2ans3))
except:
 _st_.goboom(_sage_const_117 )
try:
 _st_.current_tex_line = _sage_const_127 
 _st_.inline(_sage_const_16 , latex(p3f1))
except:
 _st_.goboom(_sage_const_127 )
try:
 _st_.current_tex_line = _sage_const_127 
 _st_.inline(_sage_const_17 , latex(p3f2))
except:
 _st_.goboom(_sage_const_127 )
try:
 _st_.current_tex_line = _sage_const_133 
 _st_.inline(_sage_const_18 , latex(p3f1))
except:
 _st_.goboom(_sage_const_133 )
try:
 _st_.current_tex_line = _sage_const_133 
 _st_.inline(_sage_const_19 , latex(p3f2))
except:
 _st_.goboom(_sage_const_133 )
try:
 _st_.current_tex_line = _sage_const_135 
 _st_.inline(_sage_const_20 , latex(p3ans1))
except:
 _st_.goboom(_sage_const_135 )
try:
 _st_.current_tex_line = _sage_const_135 
 _st_.inline(_sage_const_21 , latex(p3ans3))
except:
 _st_.goboom(_sage_const_135 )
try:
 _st_.current_tex_line = _sage_const_136 
 _st_.inline(_sage_const_22 , latex(p3ans2))
except:
 _st_.goboom(_sage_const_136 )
try:
 _st_.current_tex_line = _sage_const_136 
 _st_.inline(_sage_const_23 , latex(p3ans3))
except:
 _st_.goboom(_sage_const_136 )
try:
 _st_.current_tex_line = _sage_const_146 
 _st_.inline(_sage_const_24 , latex(p4f1))
except:
 _st_.goboom(_sage_const_146 )
try:
 _st_.current_tex_line = _sage_const_146 
 _st_.inline(_sage_const_25 , latex(p4f2))
except:
 _st_.goboom(_sage_const_146 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_26 , latex(p4f1))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_27 , latex(p4f2))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_154 
 _st_.inline(_sage_const_28 , latex(p4ans1))
except:
 _st_.goboom(_sage_const_154 )
try:
 _st_.current_tex_line = _sage_const_154 
 _st_.inline(_sage_const_29 , latex(p4ans3))
except:
 _st_.goboom(_sage_const_154 )
try:
 _st_.current_tex_line = _sage_const_155 
 _st_.inline(_sage_const_30 , latex(p4ans2))
except:
 _st_.goboom(_sage_const_155 )
try:
 _st_.current_tex_line = _sage_const_155 
 _st_.inline(_sage_const_31 , latex(p4ans3))
except:
 _st_.goboom(_sage_const_155 )
_st_.endofdoc()

